services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - mongo-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports: 
      - '8081:8081'
    environment:
      - ME_CONFIG_BASICAUTH="false"
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    depends_on:
      - mongodb
    networks:
      - mongo-network
networks:
  mongo-network:
    name: mongo-network
